name: OpenCode Command
on:
  issue_comment:
    types: [created]

jobs:
  execute:
    if: startsWith(github.event.comment.body, '/opencode') || startsWith(github.event.comment.body, '/oc')
    permissions:
      id-token: 'write'      # Required for Google Cloud handshake
      contents: 'write'      # Required to push code/branches
      pull-requests: 'write' # Required to open/comment on PRs
      issues: 'write'        # Required to comment on issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/527057980290/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gemini-app-sa-maropost-tes-198@maropost1984.iam.gserviceaccount.com'
      - uses: anomalyco/opencode/github@latest
        with:
          model: 'google-vertex/gemini-2.5-flash'
          use_github_token: true
        env:
          GOOGLE_CLOUD_PROJECT: 'maropost1984'
          GOOGLE_CLOUD_LOCATION: 'us-central1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
